language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: 5291484e15fc65c46420466bd96af82782f25a17c64e1ad618bc79feaeda0722
